<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
     <PackageReference Include="StackExchange.Redis" Version="2.7.10" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseCore.Common\BaseCore.Common.csproj" />
    <ProjectReference Include="..\BaseCore.Libs\BaseCore.Libs.csproj" />
    <ProjectReference Include="..\BaseCore.Repository\BaseCore.Repository.csproj" />
  </ItemGroup>

</Project>
